/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.healthcaremanagementsystem;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Jumana
 */
public class EmergencyPatientForm extends javax.swing.JFrame {

    /**
     * Creates new form EmergencyPatientForm
     */
    public EmergencyPatientForm() {
        initComponents();
        showDate();
        showTime();
    }
    void showDate(){
    Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        datelab.setText(s.format(d));
    }
    
    void showTime(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date d=new Date();
            SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
            timelab.setText(s.format(d));
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }).start();
        
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datelab = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        uytre = new javax.swing.JLabel();
        kjhgf = new javax.swing.JLabel();
        JHGF = new javax.swing.JLabel();
        sdfgh = new javax.swing.JLabel();
        pmmm = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hgfd = new javax.swing.JLabel();
        nvrjgnvf = new javax.swing.JLabel();
        symp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pn = new javax.swing.JTextField();
        pnID = new javax.swing.JTextField();
        pgender = new javax.swing.JTextField();
        paddress = new javax.swing.JTextField();
        pm = new javax.swing.JTextField();
        proomno = new javax.swing.JTextField();
        pphoneno = new javax.swing.JTextField();
        concussion = new javax.swing.JCheckBox();
        coughingblood = new javax.swing.JCheckBox();
        internalbleeding = new javax.swing.JCheckBox();
        chesttightness = new javax.swing.JCheckBox();
        seizure = new javax.swing.JCheckBox();
        impairedvision = new javax.swing.JCheckBox();
        covid19 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        doc = new javax.swing.JComboBox<>();
        cd = new javax.swing.JTextField();
        payment = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jumana\\Desktop\\final resize.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Emergency Patient Form");

        datelab.setText("Date:");

        timelab.setText("Time:");

        uytre.setText("Name:");

        kjhgf.setText("National ID:");

        JHGF.setText("Gender:");

        sdfgh.setText("Address:");

        pmmm.setText("PaymentMethod:");

        jLabel10.setText("Choose Doctor:");

        hgfd.setText("Room no:");

        nvrjgnvf.setText("Phone Number:");

        symp.setText("Symptoms:");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmActionPerformed(evt);
            }
        });

        concussion.setText("Concussion");

        coughingblood.setText("Coughing blood");
        coughingblood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coughingbloodActionPerformed(evt);
            }
        });

        internalbleeding.setText("Internal bleeding");

        chesttightness.setText("Chest tightness");

        seizure.setText("Seizure");

        impairedvision.setText("Impaired vision");

        covid19.setText("Covid-19");

        jCheckBox8.setText("Other");

        doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Meredith Grey", "Dr. Mark Sloan", "Dr. Derek Shepard", "Dr. Christina Yang", "Dr. Lexie Grey", "Dr. Alex Karev", "Dr. Miranda Bailey", " ", " " }));

        payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "visa" }));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datelab)
                        .addGap(105, 105, 105)
                        .addComponent(timelab)
                        .addGap(97, 97, 97))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kjhgf)
                            .addComponent(uytre)
                            .addComponent(JHGF)
                            .addComponent(sdfgh))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pgender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paddress, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(pn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(hgfd))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proomno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pmmm)
                        .addGap(18, 18, 18)
                        .addComponent(payment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nvrjgnvf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(symp)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(concussion)
                                    .addComponent(internalbleeding)
                                    .addComponent(seizure)
                                    .addComponent(covid19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coughingblood)
                                    .addComponent(chesttightness)
                                    .addComponent(impairedvision)
                                    .addComponent(jCheckBox8))
                                .addGap(65, 65, 65))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datelab)
                            .addComponent(timelab)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uytre)
                    .addComponent(nvrjgnvf)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kjhgf)
                    .addComponent(symp)
                    .addComponent(pnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concussion)
                    .addComponent(coughingblood))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JHGF)
                            .addComponent(pgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(internalbleeding)
                            .addComponent(chesttightness))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdfgh)
                    .addComponent(paddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seizure)
                    .addComponent(impairedvision))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(covid19)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pmmm)
                    .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hgfd))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmActionPerformed

    private void coughingbloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coughingbloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coughingbloodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     EmergencyPatient p;
        Hospital.addEmergencyPatient(proomno.getText(), pgender.getText(),payment.getSelectedItem().toString(), null, null, pn.getText(), pnID.getText(), pphoneno.getText(), 0, paddress.getText() );
      
       cd.setText( doc.getSelectedItem().toString());
       pm.setText( payment.getSelectedItem().toString());
       
         for(int i=0; i< Hospital.emergencypatientslist.size(); i++)
       {
           if(Hospital.emergencypatientslist.get(i).getNationalID().equals(kjhgf.getText())){
               
          if (concussion.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("fever");
        }
          if (covid19.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("dizziness");
        }
          if (impairedvision.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("sneezing");
        }
          if (internalbleeding.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("coughing");
        }
          if (seizure.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("low blood pressure");
        }
          if (coughingblood.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("high blood pressure");
        }
          if (chesttightness.isSelected()){
            Hospital.emergencypatientslist.get(i).setSymptoms("migranes");
        }
               }
           }
          
       JOptionPane.showMessageDialog(rootPane, "Patient Name: " + pn.getText() + "\nNational ID: "+ pnID.getText() + "\n\n Data has been submitted successfully ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         MenuPage obj = new MenuPage();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmergencyPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmergencyPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmergencyPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmergencyPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmergencyPatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JHGF;
    private javax.swing.JTextField cd;
    private javax.swing.JCheckBox chesttightness;
    private javax.swing.JCheckBox concussion;
    private javax.swing.JCheckBox coughingblood;
    private javax.swing.JCheckBox covid19;
    private javax.swing.JLabel datelab;
    private javax.swing.JComboBox<String> doc;
    private javax.swing.JLabel hgfd;
    private javax.swing.JCheckBox impairedvision;
    private javax.swing.JCheckBox internalbleeding;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kjhgf;
    private javax.swing.JLabel nvrjgnvf;
    private javax.swing.JTextField paddress;
    private javax.swing.JComboBox<String> payment;
    private javax.swing.JTextField pgender;
    private javax.swing.JTextField pm;
    private javax.swing.JLabel pmmm;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField pnID;
    private javax.swing.JTextField pphoneno;
    private javax.swing.JTextField proomno;
    private javax.swing.JLabel sdfgh;
    private javax.swing.JCheckBox seizure;
    private javax.swing.JLabel symp;
    private javax.swing.JLabel timelab;
    private javax.swing.JLabel uytre;
    // End of variables declaration//GEN-END:variables
}
